# Введение. Полносвязные слои. Функции активации (ноутбук)

> Начнем осваивать библиотеку `PyTorch`. Познакомимся с нейронными сетями.

## План ноутбука

1. Установка `PyTorch`
1. Введение в `PyTorch`
1. Полносвязные слои и функции активации в `PyTorch`
1. Градиентный спуск своими руками

## Установка `PyTorch`

Мы будем использовать библиотеку для глубинного обучения `PyTorch`, ее можно не устанавливать, будем пользоваться сайтом [kaggle.com](kaggle.com) для обучения в облаке (или с учителем?). 

Чтобы установить `PyTorch` локально себе на компьютер нужно ответить на два вопроса - какая у вас операционная система и есть ли у вас дискретная видеокарта (GPU) и если есть, то какого производителя. В зависимости от ваших ответов мы получаем три варианта по операционной системе - Linux, Mac и Windows; три варианта по дискретной видеокарте - нет видеокарты (доступен только центральный процессор CPU), есть видеокарта от Nvidia или есть видеокарта от AMD (это производитель именно чипа, конечный вендор может быть другой, например, ASUS, MSI, Palit). Работа с PyTorch с видеокартой от AMD это экзотика, которая выходит за рамки нашего курса, поэтому рассмотрим только варианты *нет видеокарты*/*есть видеокарта от Nvidia*.


Выберите на [сайте](https://pytorch.org/get-started/locally/) подходящие вам варианты операционной системы/видеокарты и скопируйте команду для установки. Разберем подробно самые популярные варианты установки:

### Установка в Linux ([поддерживаемые дистрибутивы](https://pytorch.org/get-started/locally/#supported-linux-distributions))

На линуксе будет работать поддержка `PyTorch` в любой конфигурации, что у вас нет видеокарты, что есть от Nvidia, что от AMD. 

Пререквизит для работы с видеокартой от Nvidia - нужно поставить CUDA, это инструмент от компании Nvidia, который позволяет ускорять вычисления на их же ГПУ. Чтобы поставить себе на машину все правильно воспользуйтесь этим [гайдом](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html) от Nvidia.

 - **pip**

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu` для тех, у кого нет видеокарты.

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116` для тех, у кого есть видеокарта (либо другой `--extra-index-url`, смотрите на сайте PyTorch, в зависимости от версии CUDA).

 - **conda**

`conda install pytorch torchvision torchaudio cpuonly -c pytorch` для тех, у кого нет видеокарты.

`conda install pytorch torchvision torchaudio cudatoolkit=11.6 -c pytorch -c conda-forge` для тех, у кого есть видеокарта (либо немного другая команда, в зависимости от версии CUDA).

### Установка в Windows

На винде будет работать поддержка `PyTorch` только для видеокарт от Nvidia и без видеокарт вообще. 

Пререквизит для работы с видеокартой от Nvidia - нужно поставить CUDA, это инструмент от компании Nvidia, который позволяет ускорять вычисления на их же ГПУ. Чтобы поставить себе на машину все правильно воспользуйтесь этим [гайдом](https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html) от Nvidia.

 - **pip**

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu` для тех, у кого нет видеокарты.

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116` для тех, у кого есть видеокарта (либо другой `--extra-index-url`, смотрите на сайте PyTorch, в зависимости от версии CUDA).

 - **conda**

`conda install pytorch torchvision torchaudio cpuonly -c pytorch` для тех, у кого нет видеокарты.

`conda install pytorch torchvision torchaudio cudatoolkit=11.6 -c pytorch -c conda-forge` для тех, у кого есть видеокарта (либо немного другая команда, в зависимости от версии CUDA).



### Установка на Mac

На маках есть пока что поддержка `PyTorch` только центрального процессора, чуть позже появится поддержка ускорения на чипах M1, M2, M1 Pro и так далее.

 - **pip**

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu` 

 - **conda**

`conda install pytorch torchvision torchaudio cpuonly -c pytorch`

## Введение в `PyTorch`

### Тензоры

Тензоры — это специализированная структура данных, по сути это массивы и матрицы. Тензоры очень похожи на массивы в numpy, так что, если у вас хорошо с numpy, то разобраться в PyTorch тензорах будет очень просто. В PyTorch мы используем тензоры для кодирования входных и выходных данных модели, а также параметров модели.

In [1]:
import torch
import numpy as np

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

### Создание тензоров

Тензор можно создать напрямую из каких-то данных - нам подходят все списки с числами:

In [3]:
some_data = [1, 2, 3, 4]
some_tensor = torch.tensor(some_data)

some_tensor

tensor([1, 2, 3, 4])

In [4]:
some_data = [[1, 2], [3, 4], [5, 6]]
some_tensor = torch.tensor(some_data)

some_tensor

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [5]:
some_data = [[[1], [2]], [[3], [4]], [[5], [6]]]
some_tensor = torch.tensor(some_data)

some_tensor

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])

In [8]:
a = np.array([1, 2, 3])
b = torch.tensor(a)

In [9]:
b[0] = -1
a

array([1, 2, 3])

In [10]:
b = torch.from_numpy(a)
b[0] = -1
a

array([-1,  2,  3])

In [11]:
c = b.to("cuda:0")
c

tensor([-1,  2,  3], device='cuda:0')

In [12]:
c[0] = 1
a

array([-1,  2,  3])

На самом деле про "все" списки с числами - обман. Если у вашего списка есть какой-то уровень вложенности, то должны совпадать размерности у всех вложенных списков (подробнее про размерности поговорим позже):

In [7]:
some_other_data = [[1, 2], [3, 4], [5, 6, 7]]
some_other_tensor = torch.tensor(some_other_data)

some_other_tensor

ValueError: expected sequence of length 2 at dim 1 (got 3)

Также тензоры можно создавать из numpy массивов и наоборот:

In [ ]:
some_numpy_array = np.array(some_data)

some_numpy_array

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

In [ ]:
some_tensor_from_numpy = torch.from_numpy(some_numpy_array)

some_tensor_from_numpy

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])

При этом если мы создаем тензор из numpy массива с помощью `torch.from_numpy`, то они делят между собой память, где лежат их данные и, соответственно, при изменении тензора меняется numpy массив и наоборот:

In [ ]:
x = np.ones(10)
y = torch.from_numpy(x)

x, y

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64))

In [ ]:
x += 1

x, y

(array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]),
 tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.], dtype=torch.float64))

In [ ]:
x = torch.ones(10)
y = x.numpy()

x, y

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
x += 1

x, y

(tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.], dtype=float32))

Можем создать тензор со случайными или константными значениями:

In [13]:
shape = (2, 3)

random_tensor = torch.randn(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
empty_tensor = torch.empty(shape)

print(random_tensor)
print(ones_tensor)
print(zeros_tensor) 
print(empty_tensor)

tensor([[-0.7653,  1.3169,  0.1505],
        [ 1.0771, -0.2559,  0.1218]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


Теперь поговорим про размерности подробнее.

У тензора есть какой-то размер, какая форма. Первое с чем нужно определиться, какой **размерности** тензор - количество осей у него.

In [14]:
c.shape

torch.Size([3])

In [15]:
c

tensor([1, 2, 3], device='cuda:0')

In [16]:
d = torch.tensor([[1, 2], [1, 2]])
d

tensor([[1, 2],
        [1, 2]])

In [17]:
d.shape

torch.Size([2, 2])

In [ ]:
shape = (10)  # одна ось (вектор)

tensor = torch.rand(shape)

tensor

tensor([0.2560, 0.9379, 0.6417, 0.5229, 0.8069, 0.4212, 0.0097, 0.7956, 0.5459,
        0.2644])

In [ ]:
shape = (2, 3)  # две оси (матрица)

tensor = torch.rand(shape)

tensor

tensor([[0.0559, 0.2930, 0.9226],
        [0.0079, 0.0833, 0.0602]])

In [ ]:
shape = (3, 2, 3)  # три оси (и больше - тензор)

tensor = torch.rand(shape)

tensor

tensor([[[0.3993, 0.4952, 0.0413],
         [0.6340, 0.6229, 0.8200]],

        [[0.7292, 0.2421, 0.7074],
         [0.0581, 0.0137, 0.0532]],

        [[0.9352, 0.7882, 0.3498],
         [0.9770, 0.3449, 0.2242]]])

Тензор с размерностью 1 - это просто вектор, список чисел.

Тензор с размерностью 2 - это просто матрица, то есть список списков чисел.

Тензор с размерностью 3 и больше - это тензор, то есть список списков списков ... чисел.

Получить доступ к размеру уже созданного тензора - метод `.shape`:

In [ ]:
some_data = [[[1], [2]], [[3], [4]], [[5], [6]]]
some_tensor = torch.tensor(some_data)

print(some_tensor)
print(some_tensor.shape)

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])
torch.Size([3, 2, 1])


В лекции мы говорили про изображения, давайте сделаем тензор, который будет нам имитировать изображение - сделаем его размер `(c, h, w)`, где `h` и `w` это его высота и ширина, а `c` - число каналов в цветовом пространстве (в черно-белом 1, в RGB 3):

In [ ]:
shape = (h, w, c)  # numpy

In [ ]:
shape = (c, h, w)  # torch

In [19]:
h = 9
w = 16
c = 3

shape = (c, h, w)

image_tensor = torch.rand(shape)

image_tensor

tensor([[[1.0140e-01, 2.4642e-01, 8.0393e-01, 9.3969e-01, 8.5649e-01,
          2.5389e-01, 9.9779e-01, 9.8726e-02, 9.7752e-01, 8.4206e-01,
          3.5622e-01, 2.2354e-01, 3.2508e-01, 7.6454e-01, 3.4762e-01,
          5.1990e-01],
         [1.7124e-01, 7.3216e-01, 8.6255e-01, 6.3095e-01, 9.9924e-01,
          4.2302e-01, 9.3682e-01, 8.5350e-01, 1.6242e-01, 9.4464e-01,
          2.4762e-01, 2.5934e-01, 6.7765e-01, 5.1041e-02, 4.1614e-01,
          4.8299e-01],
         [5.0595e-01, 2.6622e-01, 1.8791e-01, 5.4442e-01, 7.5468e-02,
          7.9483e-01, 4.0687e-01, 1.5340e-01, 2.3708e-01, 7.5340e-01,
          5.0144e-01, 7.0155e-01, 3.7440e-02, 1.0609e-01, 3.7512e-01,
          1.5700e-02],
         [8.8738e-01, 9.9987e-01, 4.9596e-01, 3.8853e-01, 9.0138e-01,
          8.2520e-01, 8.6925e-01, 9.2815e-01, 8.5832e-01, 9.7568e-01,
          3.4480e-01, 2.3270e-01, 4.0151e-01, 8.1755e-02, 2.9266e-01,
          7.4636e-01],
         [5.3463e-01, 2.4072e-01, 5.4817e-02, 5.6752e-01, 9.7849e-01

In [ ]:
image_tensor.shape

torch.Size([3, 9, 16])

Можем попробовать поменять размер тензора, например, [вытянуть его в вектор](https://pytorch.org/docs/stable/generated/torch.ravel.html):

In [20]:
image_tensor.flatten()

tensor([1.0140e-01, 2.4642e-01, 8.0393e-01, 9.3969e-01, 8.5649e-01, 2.5389e-01,
        9.9779e-01, 9.8726e-02, 9.7752e-01, 8.4206e-01, 3.5622e-01, 2.2354e-01,
        3.2508e-01, 7.6454e-01, 3.4762e-01, 5.1990e-01, 1.7124e-01, 7.3216e-01,
        8.6255e-01, 6.3095e-01, 9.9924e-01, 4.2302e-01, 9.3682e-01, 8.5350e-01,
        1.6242e-01, 9.4464e-01, 2.4762e-01, 2.5934e-01, 6.7765e-01, 5.1041e-02,
        4.1614e-01, 4.8299e-01, 5.0595e-01, 2.6622e-01, 1.8791e-01, 5.4442e-01,
        7.5468e-02, 7.9483e-01, 4.0687e-01, 1.5340e-01, 2.3708e-01, 7.5340e-01,
        5.0144e-01, 7.0155e-01, 3.7440e-02, 1.0609e-01, 3.7512e-01, 1.5700e-02,
        8.8738e-01, 9.9987e-01, 4.9596e-01, 3.8853e-01, 9.0138e-01, 8.2520e-01,
        8.6925e-01, 9.2815e-01, 8.5832e-01, 9.7568e-01, 3.4480e-01, 2.3270e-01,
        4.0151e-01, 8.1755e-02, 2.9266e-01, 7.4636e-01, 5.3463e-01, 2.4072e-01,
        5.4817e-02, 5.6752e-01, 9.7849e-01, 9.5184e-01, 8.2717e-01, 2.5478e-01,
        2.2927e-01, 2.9749e-02, 5.0066e-

In [21]:
image_tensor.ravel().shape

torch.Size([432])

In [ ]:
h * w * c

432

In [26]:
a = torch.arange(12)
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
a.reshape([2, 2, 3])

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])

In [35]:
a.reshape([2, 2, 3]).swapaxes(0, 2).flatten()

tensor([ 0,  6,  3,  9,  1,  7,  4, 10,  2,  8,  5, 11])

Посчитаем количество элементов в тензоре с помощью [специальной функции](https://pytorch.org/docs/stable/generated/torch.numel.html):

In [ ]:
image_tensor.numel()

432

In [ ]:
h = 2
w = 3
c = 3

shape = (c, h, w)

image_tensor = torch.rand(shape)

image_tensor

tensor([[[0.0260, 0.5321, 0.8319],
         [0.8304, 0.5789, 0.3981]],

        [[0.5885, 0.2135, 0.3219],
         [0.3482, 0.2303, 0.0958]],

        [[0.6992, 0.2370, 0.6614],
         [0.0874, 0.5682, 0.1406]]])

Попробуем поменять размер с помощью функции [reshape](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape):

In [ ]:
image_tensor.reshape(c, h * w)

tensor([[0.2949, 0.6946, 0.3977, 0.4057, 0.6880, 0.9954, 0.7357, 0.3604, 0.0592,
         0.1223, 0.8141, 0.8485, 0.6304, 0.5291, 0.9158, 0.2867, 0.4638, 0.4052,
         0.8572, 0.9300, 0.1590, 0.1208, 0.8563, 0.4530, 0.6034, 0.7110, 0.3972,
         0.3716, 0.5773, 0.5198, 0.5977, 0.8108, 0.6948, 0.2181, 0.9889, 0.5124,
         0.2245, 0.3009, 0.4103, 0.5378, 0.7738, 0.1619, 0.9717, 0.0947, 0.5098,
         0.2336, 0.1076, 0.0333, 0.6614, 0.9526, 0.5016, 0.5679, 0.5234, 0.1649,
         0.6341, 0.4258, 0.3450, 0.9286, 0.8990, 0.4064, 0.9994, 0.4070, 0.8882,
         0.4921, 0.3712, 0.4033, 0.2478, 0.4273, 0.3231, 0.7836, 0.3489, 0.2103,
         0.6756, 0.0127, 0.5606, 0.4380, 0.4447, 0.2431, 0.5324, 0.2058, 0.5607,
         0.7632, 0.7098, 0.0629, 0.3411, 0.6229, 0.8610, 0.5598, 0.5682, 0.7224,
         0.3799, 0.5182, 0.6789, 0.1812, 0.4476, 0.7362, 0.0224, 0.3352, 0.2837,
         0.7480, 0.0323, 0.3490, 0.8019, 0.4910, 0.5104, 0.9195, 0.0931, 0.7398,
         0.5069, 0.1076, 0.0

In [ ]:
image_tensor.reshape(c, h * w).reshape(-1, h, w).shape


torch.Size([3, 9, 16])

Попробуем собрать из нескольких тензоров один большой:

[torch.cat](https://pytorch.org/docs/stable/generated/torch.cat.html#torch.cat)

Важно помнить, что в тензорах, которые планируется конкатенировать все размерности кроме той, по которой происходиит конкатенация, должны совпадать

In [36]:
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
b = torch.randn_like(a, dtype=torch.float)
a + b

tensor([ 0.4025,  1.6418,  3.4913,  4.1228,  3.6142,  5.5530,  6.7273,  6.0795,
         6.1785,  7.8497, 11.7591, 11.2999])

In [42]:
x = torch.randn(2, 3)
y = torch.randn_like(x)

In [44]:
x

tensor([[-0.0859, -0.6193, -0.1746],
        [-0.8474, -0.0084,  2.3809]])

In [43]:
y

tensor([[-2.4154, -0.1630,  0.0842],
        [-0.9715,  0.9781,  0.0159]])

In [46]:
torch.cat([x, y], dim=0)

tensor([[-0.0859, -0.6193, -0.1746],
        [-0.8474, -0.0084,  2.3809],
        [-2.4154, -0.1630,  0.0842],
        [-0.9715,  0.9781,  0.0159]])

In [47]:
torch.cat((x, y), dim=1)

tensor([[-0.0859, -0.6193, -0.1746, -2.4154, -0.1630,  0.0842],
        [-0.8474, -0.0084,  2.3809, -0.9715,  0.9781,  0.0159]])

In [ ]:
x = torch.randn(3, 3, 1)
y = torch.randn(5, 3, 1)
z = torch.randn(1, 3, 1)

for tensor in [x, y, z]:
    print(tensor)

torch.cat((x, y, z), dim=0)

tensor([[[-1.0996],
         [ 0.8870],
         [-0.6228]],

        [[ 0.2182],
         [-0.0984],
         [ 1.8739]],

        [[-0.2601],
         [-0.3606],
         [ 1.5824]]])
tensor([[[-0.6973],
         [ 0.8779],
         [-0.9715]],

        [[ 1.9083],
         [ 0.9880],
         [-1.1860]],

        [[-0.5247],
         [-0.2767],
         [ 0.8874]],

        [[ 1.5901],
         [ 0.3149],
         [-0.3506]],

        [[ 0.0619],
         [-0.2136],
         [ 0.2138]]])
tensor([[[-0.8409],
         [-0.1382],
         [-1.8849]]])


tensor([[[-1.0996],
         [ 0.8870],
         [-0.6228]],

        [[ 0.2182],
         [-0.0984],
         [ 1.8739]],

        [[-0.2601],
         [-0.3606],
         [ 1.5824]],

        [[-0.6973],
         [ 0.8779],
         [-0.9715]],

        [[ 1.9083],
         [ 0.9880],
         [-1.1860]],

        [[-0.5247],
         [-0.2767],
         [ 0.8874]],

        [[ 1.5901],
         [ 0.3149],
         [-0.3506]],

        [[ 0.0619],
         [-0.2136],
         [ 0.2138]],

        [[-0.8409],
         [-0.1382],
         [-1.8849]]])

In [48]:
x = torch.randn(3, 3, 1)
y = torch.randn(5, 3, 2) #размерность y не совпадает 
z = torch.randn(1, 3, 1)

for tensor in [x, y, z]:
    print(tensor)

torch.cat((x, y, z), dim=0)

tensor([[[ 2.0599e-01],
         [-1.5538e+00],
         [ 6.8786e-01]],

        [[-1.2918e+00],
         [-9.5494e-04],
         [-1.8852e+00]],

        [[-2.8690e-01],
         [ 7.5325e-01],
         [ 6.6791e-01]]])
tensor([[[ 0.1120, -0.2168],
         [-0.5894,  2.9537],
         [-0.7515,  0.6161]],

        [[-0.1843,  1.4034],
         [-0.1575, -0.9925],
         [-0.9296, -1.6669]],

        [[ 1.8203,  0.8333],
         [ 1.1095, -0.1926],
         [-1.0859, -0.7623]],

        [[ 0.7722,  0.5206],
         [ 0.9806,  0.6359],
         [-1.1908,  0.4714]],

        [[-1.0493, -0.3733],
         [ 0.3750,  0.7499],
         [-1.2848,  0.7691]]])
tensor([[[ 1.1811],
         [-1.6493],
         [ 1.1299]]])


RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 1 but got size 2 for tensor number 1 in the list.

In [50]:
x = torch.randn(2, 3)
y = torch.randn(2, 5)
z = torch.randn(2, 1)

for tensor in [x, y, z]:
    print(tensor)

torch.cat((x, y, z), dim=1)

tensor([[-0.1738,  0.1036, -1.0324],
        [-0.7696,  1.0251,  1.6378]])
tensor([[-0.2498,  0.5532, -0.6359, -0.1115, -0.5017],
        [ 0.7331,  1.0725,  0.7739, -0.1870, -0.6978]])
tensor([[-0.5738],
        [ 0.6600]])


tensor([[-0.1738,  0.1036, -1.0324, -0.2498,  0.5532, -0.6359, -0.1115, -0.5017,
         -0.5738],
        [-0.7696,  1.0251,  1.6378,  0.7331,  1.0725,  0.7739, -0.1870, -0.6978,
          0.6600]])

Теперь добавим дополнительную ось:

[torch.unsqueeze](https://pytorch.org/docs/stable/generated/torch.unsqueeze.html)

In [51]:
x = torch.tensor([1, 2, 3])
x.unsqueeze(0)

tensor([[1, 2, 3]])

In [52]:
x = torch.rand(2, 3)

print(x)
print()
print(x.unsqueeze(0), x.unsqueeze(0).shape)
print()
print(x.unsqueeze(1), x.unsqueeze(1).shape)
print()
print(x.unsqueeze(2), x.unsqueeze(2).shape)

tensor([[0.9432, 0.7833, 0.1356],
        [0.9320, 0.9911, 0.9981]])

tensor([[[0.9432, 0.7833, 0.1356],
         [0.9320, 0.9911, 0.9981]]]) torch.Size([1, 2, 3])

tensor([[[0.9432, 0.7833, 0.1356]],

        [[0.9320, 0.9911, 0.9981]]]) torch.Size([2, 1, 3])

tensor([[[0.9432],
         [0.7833],
         [0.1356]],

        [[0.9320],
         [0.9911],
         [0.9981]]]) torch.Size([2, 3, 1])


Можно еще заменить unsqueeze на None в соответсвующей размерности

In [2]:
x.shape, x[None, :, :].shape

(torch.Size([2, 3]), torch.Size([1, 2, 3]))

Уберем лишние оси (где размер единичка):

In [54]:
x = torch.rand(1, 2, 1, 3)

print(x)
print()
print(x.squeeze(), x.squeeze().shape)
print()
print(x.squeeze(0), x.squeeze(0).shape)

tensor([[[[0.0802, 0.9211, 0.2741]],

         [[0.7667, 0.1818, 0.9038]]]])

tensor([[0.0802, 0.9211, 0.2741],
        [0.7667, 0.1818, 0.9038]]) torch.Size([2, 3])

tensor([[[0.0802, 0.9211, 0.2741]],

        [[0.7667, 0.1818, 0.9038]]]) torch.Size([2, 1, 3])


Теперь поговорим про типы данных в тензорах. По умолчанию в тензорах лежат числа в torch.float32 для вещественных и torch.int64 для целочисленных.

In [ ]:
tensor = torch.tensor([1.5, 2.2, 3.7, 4.9])

tensor

tensor([1.5000, 2.2000, 3.7000, 4.9000])

In [ ]:
tensor.dtype

torch.float32

In [ ]:
tensor = torch.tensor([1.5, 2.2, 3.7, 4.9], dtype=torch.float16)

tensor

tensor([1.5000, 2.1992, 3.6992, 4.8984], dtype=torch.float16)

In [ ]:
tensor = torch.tensor([1.5, 2.2, 3.7, 4.9], dtype=torch.float64)

tensor

tensor([1.5000, 2.2000, 3.7000, 4.9000], dtype=torch.float64)

In [ ]:
tensor = torch.tensor([15, 22, 37, 49])

tensor

tensor([15, 22, 37, 49])

In [ ]:
tensor.dtype

torch.int64

In [ ]:
tensor = torch.tensor([15, 22, 37, 49], dtype=torch.int32)

tensor

tensor([15, 22, 37, 49], dtype=torch.int32)

In [ ]:
tensor = torch.tensor([15, 22, 37, 49], dtype=torch.int16)

tensor

tensor([15, 22, 37, 49], dtype=torch.int16)

In [ ]:
torch.rand((1, 3, 4), dtype=torch.float32).dtype

torch.float32

Размещение тензора на GPU:

In [55]:
import torch

In [56]:
print(torch.cuda.is_available())
print(torch.cuda.get_device_name())

True
NVIDIA GeForce RTX 3090


In [57]:
! nvidia-smi

Fri Sep 29 18:47:46 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.43.04    Driver Version: 515.43.04    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
| 30%   29C    P8    23W / 370W |    395MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [58]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

print(device)

cuda:0


In [59]:
tensor = torch.tensor([15, 22, 37, 49], device=device)

tensor.to(device)

tensor([15, 22, 37, 49], device='cuda:0')

In [ ]:
tensor = torch.tensor([15, 22, 37, 49])

print(tensor)

tensor = tensor.to(device)

tensor

tensor([15, 22, 37, 49])


tensor([15, 22, 37, 49], device='cuda:0')

In [ ]:
tensor.to(torch.int32)

tensor([15, 22, 37, 49], device='cuda:0', dtype=torch.int32)

In [ ]:
tensor = tensor.cpu()

tensor

tensor([15, 22, 37, 49])

In [60]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

a + b

tensor([[1.5960, 1.3589, 0.6230],
        [0.9393, 1.7910, 0.9600]])

In [61]:
a = a.to(device)

a + b

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [ ]:
b = b.to(device)

a + b

tensor([[0.4449, 1.0726, 1.1576],
        [1.8336, 0.5651, 0.9005]], device='cuda:0')

### Операции с тензорами

Большая часть операций с тензорами хорошо описана в их [документации](https://pytorch.org/docs/stable/torch.html), разберем основные:

In [ ]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

a, b

(tensor([[0.0542, 0.3823, 0.5019],
         [0.7535, 0.0122, 0.9364]]),
 tensor([[0.9840, 0.0882, 0.7651],
         [0.7870, 0.4985, 0.0727]]))

In [ ]:
# поэлементные

print(a + b)

print()

print(torch.add(a, b))

print()

print(a.add(b))

tensor([[1.0383, 0.4705, 1.2670],
        [1.5404, 0.5107, 1.0090]])

tensor([[1.0383, 0.4705, 1.2670],
        [1.5404, 0.5107, 1.0090]])

tensor([[1.0383, 0.4705, 1.2670],
        [1.5404, 0.5107, 1.0090]])


In [ ]:
print(a - b)

print()

print(torch.sub(a, b))

print()

print(a.sub(b))

tensor([[-0.9298,  0.2940, -0.2632],
        [-0.0335, -0.4864,  0.8637]])

tensor([[-0.9298,  0.2940, -0.2632],
        [-0.0335, -0.4864,  0.8637]])

tensor([[-0.9298,  0.2940, -0.2632],
        [-0.0335, -0.4864,  0.8637]])


In [ ]:
print(a * b)

print()

print(torch.mul(a, b))

print()

print(a.mul(b))

tensor([[0.0534, 0.0337, 0.3840],
        [0.5929, 0.0061, 0.0680]])

tensor([[0.0534, 0.0337, 0.3840],
        [0.5929, 0.0061, 0.0680]])

tensor([[0.0534, 0.0337, 0.3840],
        [0.5929, 0.0061, 0.0680]])


In [ ]:
print(a / b)

print()

print(torch.div(a, b))

print()

print(a.div(b))

tensor([[ 0.0551,  4.3328,  0.6560],
        [ 0.9574,  0.0244, 12.8874]])

tensor([[ 0.0551,  4.3328,  0.6560],
        [ 0.9574,  0.0244, 12.8874]])

tensor([[ 0.0551,  4.3328,  0.6560],
        [ 0.9574,  0.0244, 12.8874]])


In [62]:
a = torch.rand(2, 3)
b = torch.rand(3, 4)
c = torch.rand(5, 5)

a, b, c

(tensor([[0.5521, 0.5774, 0.1383],
         [0.6714, 0.9636, 0.9908]]),
 tensor([[0.3551, 0.6535, 0.3463, 0.1253],
         [0.5997, 0.9538, 0.2726, 0.7810],
         [0.2266, 0.7590, 0.3964, 0.9586]]),
 tensor([[0.9616, 0.4842, 0.1539, 0.2728, 0.1055],
         [0.3487, 0.7067, 0.3381, 0.3798, 0.9193],
         [0.3779, 0.1528, 0.1942, 0.2199, 0.0263],
         [0.9414, 0.1839, 0.0010, 0.2215, 0.3000],
         [0.3884, 0.2396, 0.5998, 0.2122, 0.7922]]))

In [64]:
# матричные операции

print(a @ b, (a @ b).shape)

print()

print(torch.matmul(a, b), torch.matmul(a, b).shape)

print()

print(c.trace())

print()

print(c.exp())

tensor([[0.5737, 1.0165, 0.4034, 0.6527],
        [1.0409, 2.1099, 0.8879, 1.7866]]) torch.Size([2, 4])

tensor([[0.5737, 1.0165, 0.4034, 0.6527],
        [1.0409, 2.1099, 0.8879, 1.7866]]) torch.Size([2, 4])

tensor(2.8762)

tensor([[2.6159, 1.6229, 1.1664, 1.3137, 1.1112],
        [1.4172, 2.0273, 1.4023, 1.4621, 2.5074],
        [1.4592, 1.1650, 1.2143, 1.2460, 1.0266],
        [2.5636, 1.2019, 1.0010, 1.2480, 1.3499],
        [1.4746, 1.2708, 1.8218, 1.2364, 2.2083]])


### [Автоматическое дифференцирование](https://pytorch.org/docs/stable/notes/autograd.html)

In [65]:
x = torch.rand(5)

x

tensor([0.7457, 0.9796, 0.9334, 0.4455, 0.5999])

In [66]:
w = torch.rand(3, 5, requires_grad=True)

w

tensor([[0.5411, 0.3350, 0.8735, 0.6997, 0.7013],
        [0.4934, 0.7489, 0.1113, 0.8750, 0.6097],
        [0.5045, 0.1526, 0.4441, 0.4012, 0.5350]], requires_grad=True)

In [67]:
w.requires_grad = True
w

tensor([[0.5411, 0.3350, 0.8735, 0.6997, 0.7013],
        [0.4934, 0.7489, 0.1113, 0.8750, 0.6097],
        [0.5045, 0.1526, 0.4441, 0.4012, 0.5350]], requires_grad=True)

In [68]:
print(w.grad)

None


In [76]:
z = w + 1

In [77]:
z.retain_grad()

In [81]:
z.grad

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [82]:
w.grad

tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]])

In [79]:
z.sum()

tensor(23.0262, grad_fn=<SumBackward0>)

In [80]:
z.sum().backward()

In [75]:
z.sum()

tensor(23.0262, grad_fn=<SumBackward0>)

In [ ]:
first_z = torch.empty(3)

first_z

tensor([2.0862e+10, 0.0000e+00, 3.3631e-44])

In [ ]:
for i in range(3):
    first_z[i] = torch.sum(w[i] * x)

first_z

tensor([0.8002, 1.3663, 1.9262], grad_fn=<CopySlices>)

In [ ]:
z = torch.matmul(x, w.t())

z

tensor([0.8002, 1.3663, 1.9262], grad_fn=<SqueezeBackward3>)

In [100]:
v = torch.rand(3, requires_grad=True)
z = torch.tensor([1, 2, 3])

v

tensor([0.4725, 0.2244, 0.2097], requires_grad=True)

In [101]:
print(v.grad)

None


In [102]:
y = torch.sum(z * v)

y

tensor(1.5503, grad_fn=<SumBackward0>)

In [103]:
y.item()

1.5502820014953613

In [104]:
loss = torch.mean((y - 2) ** 2)

In [105]:
loss.backward()

In [106]:
v.grad

tensor([-0.8994, -1.7989, -2.6983])

In [107]:
y = torch.sum(z * (v - v.grad * 0.001))
loss = torch.mean((y - 2) ** 2)
v.grad.zero_()

tensor([0., 0., 0.])

In [108]:
loss.backward()

In [118]:
v.grad

tensor([-0.8743, -1.7485, -2.6228])

In [112]:
y.detach().requires_grad

False

In [113]:
y

tensor(1.5629, grad_fn=<SumBackward0>)

In [117]:
a = torch.tensor(1., requires_grad=True)
(y.detach() + a).backward()

In [118]:
v.grad  # не поменялся

tensor([-0.8743, -1.7485, -2.6228])

In [123]:
with torch.no_grad():
    loss = torch.sum(a - b)

loss

tensor(5.5719)

In [124]:
loss.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [ ]:
a = torch.rand(3, 5, requires_grad=True)
b = torch.rand(3, 5, requires_grad=True)

a, b

(tensor([[0.3856, 0.4382, 0.2194, 0.8110, 0.3136],
         [0.5516, 0.3726, 0.6769, 0.4662, 0.0127],
         [0.6691, 0.2735, 0.0376, 0.5726, 0.0020]], requires_grad=True),
 tensor([[0.3206, 0.1292, 0.6550, 0.2735, 0.1023],
         [0.6090, 0.5692, 0.5814, 0.5776, 0.9256],
         [0.7932, 0.5164, 0.3540, 0.6253, 0.5959]], requires_grad=True))

In [ ]:
with torch.inference_mode():
    loss = torch.sum(a - b)

loss

tensor(-1.8255)

In [ ]:
loss.backward()

RuntimeError: ignored

In [ ]:
loss = torch.sum(a - b)
loss.detach()

tensor(-1.8255)

In [ ]:
with torch.no_grad():
    a = torch.rand(3, 5, requires_grad=True)
    b = torch.rand(3, 5, requires_grad=True)
    
    loss = torch.sum(a + b)
    
    print(f'loss{loss}=')
    
    loss.backward()

loss15.592167854309082=


RuntimeError: ignored

In [ ]:
loss2 = torch.sum(a + b)

loss2

tensor(15.5922, grad_fn=<SumBackward0>)

In [ ]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=None

b.grad=None



In [ ]:
loss2.backward()

In [ ]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

b.grad=tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])



In [ ]:
with torch.inference_mode():
    a = torch.rand(3, 5, requires_grad=True)
    b = torch.rand(3, 5, requires_grad=True)
    
    loss = torch.sum(a + b)
    
    print(f'{loss}=')
    
    loss.backward()

13.422080993652344=


RuntimeError: ignored

In [ ]:
with torch.no_grad():
    x = torch.randn(1)
    y = x + 1

y.requires_grad = True
z = y + 1
print(z.grad_fn, z.requires_grad)

<AddBackward0 object at 0x7fe769974410> True


In [ ]:
with torch.inference_mode():
    x = torch.randn(1)
    y = x + 1

y.requires_grad = True

RuntimeError: ignored

In [ ]:
loss2 = torch.sum(a + b)

loss2

tensor(13.4221)

In [ ]:
@torch.no_grad()
def foo():
    a = torch.rand(3, 5, requires_grad=True)
    b = torch.rand(3, 5, requires_grad=True)
    
    loss = torch.mean(a + b)
    
    print(f'{loss}')
    
    return a, b

In [ ]:
a, b = foo()

1.090566635131836


In [ ]:
torch.mean(a - b)

tensor(0.0373, grad_fn=<MeanBackward0>)

In [ ]:
@torch.inference_mode()
def foo():
    a = torch.rand(3, 5, requires_grad=True)
    b = torch.rand(3, 5, requires_grad=True)
    
    loss = torch.mean(a + b)
    
    print(f'{loss}')
    
    return a, b

In [ ]:
a, b = foo()

1.0319470167160034


In [ ]:
torch.mean(a - b)

tensor(0.1286)

In [ ]:
a.requires_grad = False

## Полносвязные слои и функции активации в `PyTorch`

In [125]:
from torch import nn

### Полносвязный слой

>$y_j = \sum\limits_{i=1}^{n}x_iw_{ji} + b_j$


In [ ]:
[n, 5]

[5, 3]

In [126]:
layer = nn.Linear(in_features=5, out_features=3)

In [127]:
layer

Linear(in_features=5, out_features=3, bias=True)

In [128]:
layer.weight

Parameter containing:
tensor([[-0.1822, -0.2018, -0.2231,  0.1934, -0.3534],
        [-0.3526, -0.0336, -0.3731, -0.1703,  0.2988],
        [-0.2046, -0.2548,  0.1474, -0.4155, -0.2342]], requires_grad=True)

In [129]:
layer.weight.shape

torch.Size([3, 5])

In [130]:
layer.bias

Parameter containing:
tensor([0.4107, 0.1643, 0.0627], requires_grad=True)

In [133]:
layer = nn.Linear(in_features=5, out_features=3, bias=False)

In [134]:
layer.bias

In [ ]:
layer.__call__

<bound method Module._call_impl of Linear(in_features=5, out_features=3, bias=False)>

In [135]:
x = torch.randn(5)

print(layer(x))

tensor([-0.1746, -0.1043, -0.0273], grad_fn=<SqueezeBackward3>)


In [137]:
layer(x).sum().backward()
layer.weight.grad

tensor([[ 1.3821, -0.1964, -1.2123, -0.3602,  0.8236],
        [ 1.3821, -0.1964, -1.2123, -0.3602,  0.8236],
        [ 1.3821, -0.1964, -1.2123, -0.3602,  0.8236]])

### Функции активации

> Сигмоида $f(x) = \dfrac{1}{1 + e^{-x}}$

In [ ]:
activation = nn.Sigmoid()

In [ ]:
x = torch.randn(5)

print(x)

print(activation(x))

tensor([ 0.4075,  0.8449,  1.2787,  2.5847, -0.7478])
tensor([0.6005, 0.6995, 0.7822, 0.9299, 0.3213])


> ReLU $f(x) = \max(0, x)$

In [ ]:
activation = nn.ReLU()

In [ ]:
x = torch.randn(5)

print(x)

print(activation(x))

tensor([ 0.6207, -0.8071, -0.4997, -0.1487,  0.4741])
tensor([0.6207, 0.0000, 0.0000, 0.0000, 0.4741])


> Leaky ReLU $f(x) = \max(0, x) + \alpha \min(0, x)$

In [ ]:
activation = nn.LeakyReLU(negative_slope=0.001)

In [ ]:
x = torch.randn(5)

print(x)

print(activation(x))

tensor([-0.3126, -0.0250, -1.3733,  1.0757,  0.1537])
tensor([-3.1262e-04, -2.4956e-05, -1.3733e-03,  1.0757e+00,  1.5374e-01])


### Код из прошлого года, для самостоятельного разбора

In [ ]:
print(f'{x.grad}=\n')
print(f'{w.grad}=\n')
print(f'{z.grad}=\n')
print(f'{v.grad}=\n')

None=

None=

None=

None=



/usr/local/lib/python3.7/dist-packages/torch/_tensor.py:1083: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  aten/src/ATen/core/TensorBody.h:477.)
  return self._grad


In [ ]:
loss.backward()

In [ ]:
loss.dtype, loss

(torch.float32, tensor(1.3859, grad_fn=<MeanBackward0>))

In [ ]:
print(f'x{x.grad}=\n')
print(f'w{w.grad}=\n')
print(f'z{z.grad}=\n')
print(f'v{v.grad}=\n')

xNone=

wtensor([[0.7890, 0.3063, 0.4679, 0.4546, 0.8373],
        [1.3126, 0.5095, 0.7784, 0.7563, 1.3931],
        [1.4398, 0.5589, 0.8539, 0.8296, 1.5280]])=

zNone=

vtensor([1.8840, 3.2169, 4.5352])=



In [ ]:
a = torch.rand(1, requires_grad=True)
b = torch.rand(1, requires_grad=True)

a, b

(tensor([0.4976], requires_grad=True), tensor([0.1180], requires_grad=True))

In [ ]:
c = a
c = c + b
c = c + a

In [ ]:
c = torch.rand((1, 2, 3))

In [ ]:
loss = (a - b)

loss

tensor([0.3796], grad_fn=<SubBackward0>)

In [ ]:
print(f'{a.grad}=\n')
print(f'{b.grad}=\n')

None=

None=



In [ ]:
loss.backward()

In [ ]:
print(f'{a.grad}=\n')  # 1
print(f'{b.grad}=\n')  # -1

tensor([1.])=

tensor([-1.])=



In [ ]:
a.grad.zero_()
b.grad.zero_()

tensor([0.])

In [ ]:
loss = (a - b) ** 2

loss

tensor([0.1441], grad_fn=<PowBackward0>)

In [ ]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=tensor([0.])

b.grad=tensor([0.])



In [ ]:
loss.backward()

In [ ]:
print(f'{a.grad=}\n')  # 2 * (a - b)
print(f'{b.grad=}\n')  # -2 * (a - b)

a.grad=tensor([0.2736])

b.grad=tensor([-0.2736])



In [ ]:
2 * (a - b)

tensor([0.2736], grad_fn=<MulBackward0>)

In [ ]:
a = torch.rand(3, 5, requires_grad=True)
b = torch.rand(3, 5, requires_grad=True)

a, b

(tensor([[0.3279, 0.5942, 0.6495, 0.8076, 0.6961],
         [0.7243, 0.3865, 0.4297, 0.0069, 0.3211],
         [0.9084, 0.0009, 0.5393, 0.4543, 0.1057]], requires_grad=True),
 tensor([[0.3158, 0.7038, 0.3901, 0.7456, 0.8604],
         [0.4813, 0.8476, 0.9554, 0.9591, 0.9958],
         [0.5856, 0.4295, 0.9476, 0.6895, 0.3585]], requires_grad=True))

In [ ]:
loss = torch.mean(a * b)

loss

tensor(0.3189, grad_fn=<MeanBackward0>)

In [ ]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=None

b.grad=None



In [ ]:
loss.backward()

In [ ]:
print(f'{a.grad=}\n')  # b / (3 * 5)
print(f'{b.grad=}\n')  # a / (3 * 5)

a.grad=tensor([[0.0211, 0.0469, 0.0260, 0.0497, 0.0574],
        [0.0321, 0.0565, 0.0637, 0.0639, 0.0664],
        [0.0390, 0.0286, 0.0632, 0.0460, 0.0239]])

b.grad=tensor([[2.1862e-02, 3.9616e-02, 4.3297e-02, 5.3840e-02, 4.6404e-02],
        [4.8289e-02, 2.5765e-02, 2.8644e-02, 4.6089e-04, 2.1404e-02],
        [6.0560e-02, 6.2525e-05, 3.5952e-02, 3.0284e-02, 7.0479e-03]])



In [ ]:
a / 15

tensor([[2.1862e-02, 3.9616e-02, 4.3297e-02, 5.3840e-02, 4.6404e-02],
        [4.8289e-02, 2.5765e-02, 2.8644e-02, 4.6089e-04, 2.1404e-02],
        [6.0560e-02, 6.2525e-05, 3.5952e-02, 3.0284e-02, 7.0479e-03]],
       grad_fn=<DivBackward0>)

In [ ]:
b / 15

tensor([[0.0211, 0.0469, 0.0260, 0.0497, 0.0574],
        [0.0321, 0.0565, 0.0637, 0.0639, 0.0664],
        [0.0390, 0.0286, 0.0632, 0.0460, 0.0239]], grad_fn=<DivBackward0>)

In [ ]:
a = torch.rand(3, 5, requires_grad=True)

print(f'{a=}\n')

loss1 = torch.sum(a ** 2) # 2a
loss2 = torch.sum(a) # 1

print(f'{a.grad=}\n')

loss1.backward()

print(f'{a.grad=}\n')

loss2.backward()

print(f'{a.grad=}\n')

a=tensor([[0.9249, 0.5178, 0.4018, 0.5241, 0.2307],
        [0.4165, 0.5878, 0.6177, 0.4664, 0.3297],
        [0.2164, 0.3102, 0.1307, 0.8902, 0.9583]], requires_grad=True)

a.grad=None

a.grad=tensor([[1.8499, 1.0356, 0.8036, 1.0483, 0.4613],
        [0.8329, 1.1757, 1.2353, 0.9329, 0.6594],
        [0.4329, 0.6204, 0.2613, 1.7805, 1.9166]])

a.grad=tensor([[2.8499, 2.0356, 1.8036, 2.0483, 1.4613],
        [1.8329, 2.1757, 2.2353, 1.9329, 1.6594],
        [1.4329, 1.6204, 1.2613, 2.7805, 2.9166]])



In [ ]:
print(f'{2*a=}\n')
print(f'{2*a+1=}')

2*a=tensor([[1.8499, 1.0356, 0.8036, 1.0483, 0.4613],
        [0.8329, 1.1757, 1.2353, 0.9329, 0.6594],
        [0.4329, 0.6204, 0.2613, 1.7805, 1.9166]], grad_fn=<MulBackward0>)

2*a+1=tensor([[2.8499, 2.0356, 1.8036, 2.0483, 1.4613],
        [1.8329, 2.1757, 2.2353, 1.9329, 1.6594],
        [1.4329, 1.6204, 1.2613, 2.7805, 2.9166]], grad_fn=<AddBackward0>)


In [ ]:
a = torch.rand(3, 5, requires_grad=True)
b = torch.rand(3, 5, requires_grad=False)

a, b

(tensor([[0.9585, 0.8137, 0.7837, 0.3117, 0.5308],
         [0.5991, 0.7310, 0.9645, 0.7374, 0.7492],
         [0.5522, 0.8426, 0.0137, 0.8135, 0.0080]], requires_grad=True),
 tensor([[0.0779, 0.3624, 0.0938, 0.1770, 0.2233],
         [0.3437, 0.3984, 0.9332, 0.7502, 0.0515],
         [0.3722, 0.6910, 0.0804, 0.5425, 0.1549]]))

In [ ]:
loss = torch.sum(a - b)

loss

tensor(4.1571, grad_fn=<SumBackward0>)

In [ ]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=None

b.grad=None



In [ ]:
loss.backward()

In [ ]:
print(f'{a.grad=}\n')  # all ones
print(f'{b.grad=}\n')  # None

a.grad=tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

b.grad=None



In [ ]:
a = torch.rand(3, 5, requires_grad=True)
b = torch.rand(3, 5, requires_grad=True)

a, b

(tensor([[0.4873, 0.0094, 0.3410, 0.6388, 0.3698],
         [0.3318, 0.3989, 0.4540, 0.8396, 0.7872],
         [0.2356, 0.5495, 0.3216, 0.0462, 0.1471]], requires_grad=True),
 tensor([[0.9219, 0.8603, 0.0196, 0.7148, 0.3156],
         [0.4160, 0.4039, 0.9161, 0.9858, 0.4589],
         [0.9566, 0.1626, 0.5449, 0.9074, 0.7661]], requires_grad=True))

## Градиентный спуск своими руками

In [ ]:
n_features = 2
n_objects = 300

torch.manual_seed(0)

w_true = torch.randn(n_features)
b_true = torch.randn(1)

x = (torch.rand(n_objects, n_features) - 0.5) * 10 * (torch.arange(n_features) * 2 + 1)
y = torch.matmul(x, w_true) + torch.randn(n_objects) + b_true

In [ ]:
x.shape, y.shape, w_true.shape, b_true.shape

(torch.Size([300, 2]), torch.Size([300]), torch.Size([2]), torch.Size([1]))

In [ ]:
n_steps = 200
step_size = 1e-2

In [ ]:
w = torch.rand(n_features, requires_grad=True)
b = torch.rand(1, requires_grad=True)

for i in range(n_steps):
    y_pred = torch.matmul(x, w) + b
    
    mse = torch.mean((y_pred - y) ** 2)
    
    if i < 20 or i % 10 == 0:
        print(f'MSE на шаге {i + 1} {mse.item():.5f}')

    mse.backward()

    with torch.no_grad():
        w -= w.grad * step_size
        b -= b.grad * step_size

    w.grad.zero_()
    b.grad.zero_()

MSE на шаге 1 23.65750
MSE на шаге 2 15.53605
MSE на шаге 3 12.11575
MSE на шаге 4 10.36995
MSE на шаге 5 9.30175
MSE на шаге 6 8.55659
MSE на шаге 7 7.99169
MSE на шаге 8 7.53972
MSE на шаге 9 7.16377
MSE на шаге 10 6.84131
MSE на шаге 11 6.55765
MSE на шаге 12 6.30292
MSE на шаге 13 6.07033
MSE на шаге 14 5.85515
MSE на шаге 15 5.65409
MSE на шаге 16 5.46478
MSE на шаге 17 5.28555
MSE на шаге 18 5.11514
MSE на шаге 19 4.95265
MSE на шаге 20 4.79736
MSE на шаге 21 4.64871
MSE на шаге 31 3.45555
MSE на шаге 41 2.65631
MSE на шаге 51 2.11964
MSE на шаге 61 1.75925
MSE на шаге 71 1.51724
MSE на шаге 81 1.35471
MSE на шаге 91 1.24558
MSE на шаге 101 1.17229
MSE на шаге 111 1.12307
MSE на шаге 121 1.09002
MSE на шаге 131 1.06782
MSE на шаге 141 1.05292
MSE на шаге 151 1.04291
MSE на шаге 161 1.03619
MSE на шаге 171 1.03168
MSE на шаге 181 1.02864
MSE на шаге 191 1.02661


In [ ]:
layer = nn.Linear(in_features=n_features, out_features=1)

for i in range(n_steps):
    y_pred = layer(x)

    mse = torch.mean((y_pred - y) ** 2)
    
    if i < 20 or i % 10 == 0:
        print(f'MSE на шаге {i + 1} {mse.item():.5f}')

    mse.backward()

    with torch.no_grad():
        layer.weight -= layer.weight.grad * step_size
        layer.bias -= layer.bias.grad * step_size

#     layer.weight.grad.zero_()
#     layer.bias.grad.zero_()
    
    layer.zero_grad()

MSE на шаге 1 61.04561
MSE на шаге 2 43.79891
MSE на шаге 3 37.83810
MSE на шаге 4 35.47980
MSE на шаге 5 34.33194
MSE на шаге 6 33.63191
MSE на шаге 7 33.12450
MSE на шаге 8 32.71631
MSE на шаге 9 32.36813
MSE на шаге 10 32.06060
MSE на шаге 11 31.78264
MSE на шаге 12 31.52728
MSE на шаге 13 31.28983
MSE на шаге 14 31.06706
MSE на шаге 15 30.85670
MSE на шаге 16 30.65709
MSE на шаге 17 30.46700
MSE на шаге 18 30.28552
MSE на шаге 19 30.11194
MSE на шаге 20 29.94569
MSE на шаге 21 29.78632
MSE на шаге 31 28.50329
MSE на шаге 41 27.64299
MSE на шаге 51 27.06530
MSE на шаге 61 26.67736
MSE на шаге 71 26.41685
MSE на шаге 81 26.24191
MSE на шаге 91 26.12442
MSE на шаге 101 26.04553
MSE на шаге 111 25.99255
MSE на шаге 121 25.95697
MSE на шаге 131 25.93308
MSE на шаге 141 25.91704
MSE на шаге 151 25.90627
MSE на шаге 161 25.89903
MSE на шаге 171 25.89417
MSE на шаге 181 25.89091
MSE на шаге 191 25.88872


In [ ]:
layer(x)

tensor([[-2.7148],
        [-2.7140],
        [-2.7176],
        [-2.7166],
        [-2.7120],
        [-2.7163],
        [-2.7139],
        [-2.7192],
        [-2.7145],
        [-2.6967],
        [-2.7170],
        [-2.7219],
        [-2.7158],
        [-2.7131],
        [-2.7239],
        [-2.7108],
        [-2.7082],
        [-2.7042],
        [-2.7162],
        [-2.7095],
        [-2.7165],
        [-2.7121],
        [-2.7090],
        [-2.7013],
        [-2.7051],
        [-2.7159],
        [-2.7101],
        [-2.7203],
        [-2.7056],
        [-2.7133],
        [-2.7121],
        [-2.7177],
        [-2.7136],
        [-2.7090],
        [-2.7043],
        [-2.7071],
        [-2.7277],
        [-2.6977],
        [-2.7091],
        [-2.7108],
        [-2.7043],
        [-2.7117],
        [-2.7072],
        [-2.7181],
        [-2.7084],
        [-2.7164],
        [-2.7069],
        [-2.7150],
        [-2.7219],
        [-2.7148],
        [-2.7137],
        [-2.7203],
        [-2.

In [ ]:
layer(x).shape

torch.Size([300, 1])

In [ ]:
y.shape

torch.Size([300])

In [ ]:
(layer(x) - y).shape

torch.Size([300, 300])

In [ ]:
(layer(x).ravel() - y).shape

torch.Size([300])

In [ ]:
layer = nn.Linear(in_features=n_features, out_features=1)

for i in range(n_steps):
    y_pred = layer(x).ravel()

    mse = torch.mean((y_pred - y) ** 2)
    
    if i < 20 or i % 10 == 0:
        print(f'MSE на шаге {i + 1} {mse.item():.5f}')

    mse.backward()

    with torch.no_grad():
        layer.weight -= layer.weight.grad * step_size
        layer.bias -= layer.bias.grad * step_size

    layer.zero_grad()

MSE на шаге 1 82.40031
MSE на шаге 2 34.83059
MSE на шаге 3 18.67639
MSE на шаге 4 12.57786
MSE на шаге 5 9.87140
MSE на шаге 6 8.42349
MSE на шаге 7 7.51441
MSE на шаге 8 6.87739
MSE на шаге 9 6.39865
MSE на шаге 10 6.02125
MSE на шаге 11 5.71254
MSE на шаге 12 5.45201
MSE на шаге 13 5.22616
MSE на шаге 14 5.02584
MSE на шаге 15 4.84476
MSE на шаге 16 4.67857
MSE на шаге 17 4.52421
MSE на шаге 18 4.37955
MSE на шаге 19 4.24304
MSE на шаге 20 4.11358
MSE на шаге 21 3.99035
MSE на шаге 31 3.01138
MSE на шаге 41 2.35799
MSE на шаге 51 1.91931
MSE на шаге 61 1.62472
MSE на шаге 71 1.42689
MSE на шаге 81 1.29405
MSE на шаге 91 1.20484
MSE на шаге 101 1.14493
MSE на шаге 111 1.10470
MSE на шаге 121 1.07768
MSE на шаге 131 1.05954
MSE на шаге 141 1.04736
MSE на шаге 151 1.03917
MSE на шаге 161 1.03368
MSE на шаге 171 1.02999
MSE на шаге 181 1.02751
MSE на шаге 191 1.02585


In [ ]:
n_features = 5
n_objects = 300

torch.manual_seed(0)

w_true = torch.randn(n_features)

x = (torch.rand(n_objects, n_features) - 0.5) * 10 * (torch.arange(n_features) * 2 + 1)
y = torch.matmul(x, w_true) + torch.randn(n_objects)

In [ ]:
n_steps = 2000
step_size = 1e-3

In [ ]:
layer = nn.Linear(in_features=n_features, out_features=1)

for i in range(n_steps):
    y_pred = layer(x).ravel()

    mse = torch.mean((y_pred - y) ** 2)
    
    if i < 20 or i % 50 == 0:
        print(f'MSE на шаге {i + 1} {mse.item():.5f}')

    mse.backward()

    with torch.no_grad():
        layer.weight -= layer.weight.grad * step_size
        layer.bias -= layer.bias.grad * step_size

    layer.zero_grad()

MSE на шаге 1 1522.64282
MSE на шаге 2 345.22867
MSE на шаге 3 134.71323
MSE на шаге 4 69.14162
MSE на шаге 5 45.61798
MSE на шаге 6 36.15922
MSE на шаге 7 31.74179
MSE на шаге 8 29.24493
MSE на шаге 9 27.53952
MSE на шаге 10 26.19924
MSE на шаге 11 25.05364
MSE на шаге 12 24.02866
MSE на шаге 13 23.08827
MSE на шаге 14 22.21260
MSE на шаге 15 21.38941
MSE на шаге 16 20.61047
MSE на шаге 17 19.86992
MSE на шаге 18 19.16343
MSE на шаге 19 18.48770
MSE на шаге 20 17.84015
MSE на шаге 51 6.27401
MSE на шаге 101 1.74083
MSE на шаге 151 1.02593
MSE на шаге 201 0.91269
MSE на шаге 251 0.89435
MSE на шаге 301 0.89104
MSE на шаге 351 0.89019
MSE на шаге 401 0.88977
MSE на шаге 451 0.88948
MSE на шаге 501 0.88925
MSE на шаге 551 0.88906
MSE на шаге 601 0.88890
MSE на шаге 651 0.88877
MSE на шаге 701 0.88867
MSE на шаге 751 0.88858
MSE на шаге 801 0.88851
MSE на шаге 851 0.88845
MSE на шаге 901 0.88840
MSE на шаге 951 0.88836
MSE на шаге 1001 0.88833
MSE на шаге 1051 0.88830
MSE на шаге 1101 0.8

In [ ]:
n_steps = 2000
step_size = 5e-4

In [ ]:
layer1 = nn.Linear(in_features=n_features, out_features=3)
layer2 = nn.Linear(in_features=3, out_features=1)
activation = nn.ReLU()


for i in range(n_steps):
    y_pred = layer2(activation(layer1(x))).ravel()

    mse = torch.mean((y_pred - y) ** 2)

    if i < 20 or i % 50 == 0:
        print(f'MSE на шаге {i + 1} {mse.item():.5f}')

    mse.backward()

    with torch.no_grad():
        layer1.weight -= layer1.weight.grad * step_size
        layer1.bias -= layer1.bias.grad * step_size
        layer2.weight -= layer2.weight.grad * step_size
        layer2.bias -= layer2.bias.grad * step_size
x
    layer1.zero_grad()
    layer2.zero_grad()

MSE на шаге 1 2065.53369
MSE на шаге 2 1888.85938
MSE на шаге 3 1850.07874
MSE на шаге 4 1825.02942
MSE на шаге 5 1791.48108
MSE на шаге 6 1741.56946
MSE на шаге 7 1664.26440
MSE на шаге 8 1554.74976
MSE на шаге 9 1436.31213
MSE на шаге 10 1332.71838
MSE на шаге 11 1251.31506
MSE на шаге 12 1172.20129
MSE на шаге 13 1067.16370
MSE на шаге 14 917.52533
MSE на шаге 15 715.28870
MSE на шаге 16 494.19235
MSE на шаге 17 321.12256
MSE на шаге 18 196.44054
MSE на шаге 19 114.49352
MSE на шаге 20 68.29835
MSE на шаге 51 6.47334
MSE на шаге 101 2.82488
MSE на шаге 151 1.49911
MSE на шаге 201 1.07840
MSE на шаге 251 0.96143
MSE на шаге 301 0.92727
MSE на шаге 351 0.91400
MSE на шаге 401 0.90641
MSE на шаге 451 0.90219
MSE на шаге 501 0.89821
MSE на шаге 551 0.89528
MSE на шаге 601 0.89345
MSE на шаге 651 0.89220
MSE на шаге 701 0.89122
MSE на шаге 751 0.88999
MSE на шаге 801 0.88914
MSE на шаге 851 0.88839
MSE на шаге 901 0.88770
MSE на шаге 951 0.88708
MSE на шаге 1001 0.88650
MSE на шаге 1051 