In [1]:
import torch
import numpy as np

In [2]:
a = np.random.normal(size=(10, 20))
a

array([[-7.24576170e-01, -1.40499652e+00, -1.01383281e-01,
        -7.32811306e-02, -1.43235991e+00, -7.61451591e-02,
         1.29578511e-01,  8.23934228e-02, -1.37029981e+00,
        -1.72021776e-01,  1.95352980e-01, -1.99764100e-01,
         5.93417850e-01,  9.55367290e-01, -3.88307055e-03,
        -9.00964803e-02,  2.00002166e-01,  1.96310056e-01,
        -4.68232870e-01,  4.66234312e-01],
       [ 1.43968900e-01,  1.28693181e+00,  2.26905546e+00,
         1.46412158e+00, -2.08340998e-02, -9.08974390e-01,
        -4.10099210e-01,  1.20536282e+00, -4.90760313e-01,
        -3.90908627e-01, -6.51912199e-02,  6.12324999e-01,
         2.10233380e-01, -5.65118454e-01,  1.28883683e+00,
         5.18070505e-01,  2.64947233e-01,  5.44061635e-01,
         5.27789098e-01,  6.51276159e-03],
       [-6.98683150e-01,  8.31343507e-01,  5.91659426e-01,
        -3.28974888e-01, -5.02347290e-01,  1.57329801e-01,
        -1.55970371e+00,  9.24112553e-01, -1.13105390e+00,
        -1.51222098e+00,  1.0

In [3]:
a.sum()

-36.989749145303385

In [4]:
(a ** 2).sum()

237.29342861729842

In [5]:
a.shape

(10, 20)

In [6]:
res = a @ a.T
res.shape

(10, 10)

In [7]:
b = torch.tensor(a)
b

tensor([[-7.2458e-01, -1.4050e+00, -1.0138e-01, -7.3281e-02, -1.4324e+00,
         -7.6145e-02,  1.2958e-01,  8.2393e-02, -1.3703e+00, -1.7202e-01,
          1.9535e-01, -1.9976e-01,  5.9342e-01,  9.5537e-01, -3.8831e-03,
         -9.0096e-02,  2.0000e-01,  1.9631e-01, -4.6823e-01,  4.6623e-01],
        [ 1.4397e-01,  1.2869e+00,  2.2691e+00,  1.4641e+00, -2.0834e-02,
         -9.0897e-01, -4.1010e-01,  1.2054e+00, -4.9076e-01, -3.9091e-01,
         -6.5191e-02,  6.1232e-01,  2.1023e-01, -5.6512e-01,  1.2888e+00,
          5.1807e-01,  2.6495e-01,  5.4406e-01,  5.2779e-01,  6.5128e-03],
        [-6.9868e-01,  8.3134e-01,  5.9166e-01, -3.2897e-01, -5.0235e-01,
          1.5733e-01, -1.5597e+00,  9.2411e-01, -1.1311e+00, -1.5122e+00,
          1.0312e-01,  1.5203e+00, -2.3545e+00,  2.4057e-01,  6.6569e-01,
          1.2103e-01, -1.8820e-01, -9.3098e-01, -1.2148e+00,  2.2628e-01],
        [-1.8729e+00, -9.5631e-02,  6.0263e-01,  1.0477e-01, -4.8507e-01,
         -1.3970e+00,  4.0832e-01, 

In [8]:
b.sum()

tensor(-36.9897, dtype=torch.float64)

In [9]:
(b ** 2).sum()

tensor(237.2934, dtype=torch.float64)

In [10]:
res = b @ b.T
res.shape

torch.Size([10, 10])

In [25]:
x = torch.tensor(2.0, requires_grad=True)
y = torch.tensor(1.0, requires_grad=True)

z = x ** 2 + y

w = torch.log(z)

In [26]:
w.backward()

In [27]:
x.grad

tensor(0.8000)

In [28]:
2 * x / (x ** 2 + y)

tensor(0.8000, grad_fn=<DivBackward0>)

In [29]:
y.grad.zero_()
a = y ** 3
a.backward()
y.grad

tensor(3.)

In [30]:
A = torch.tensor(np.random.normal(size=(20, 20)))
x = torch.tensor(np.random.normal(size=(20,)), requires_grad=True)

w = x.T @ A
y = w @ x

y.backward()

<ipython-input-30-ab53505b8363>:4: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3571.)
  w = x.T @ A


In [31]:
x.grad

tensor([ -1.7213,   7.3636,   1.7475,  -1.0971,  13.9996,  -2.6436,  -2.5549,
          5.2895, -18.6232,   5.1222,  -6.2905,   1.4286,  -5.6245,  -4.5044,
          0.9611,  -5.2643,  -3.8299,  -0.5409,   7.1427,  -7.0761],
       dtype=torch.float64)

In [32]:
(A + A.T) @ x

tensor([ -1.7213,   7.3636,   1.7475,  -1.0971,  13.9996,  -2.6436,  -2.5549,
          5.2895, -18.6232,   5.1222,  -6.2905,   1.4286,  -5.6245,  -4.5044,
          0.9611,  -5.2643,  -3.8299,  -0.5409,   7.1427,  -7.0761],
       dtype=torch.float64, grad_fn=<MvBackward0>)

In [33]:
x = torch.tensor(2.0, requires_grad=True)
y = torch.abs(x)
y.backward()
x.grad

tensor(1.)

In [34]:
import pandas as pd
import numpy as np

data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
x = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
y = raw_df.values[1::2, 2]

In [35]:
from sklearn.model_selection import train_test_split

train_idx, test_idx = train_test_split(np.arange(len(x)), test_size=0.3, shuffle=True, random_state=0)

x_train, y_train = x[train_idx], y[train_idx]
x_test, y_test = x[test_idx], y[test_idx]

In [36]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [37]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

model = LinearRegression().fit(x_train, y_train)
pred = model.predict(x_test)

mean_squared_error(pred, y_test)

27.195965766883198

In [38]:
x_train.shape

(354, 13)

In [39]:
x_t = torch.tensor(x_train).float()
y_t = torch.tensor(y_train).float()
x_test_t = torch.tensor(x_test).float()
y_test_t = torch.tensor(y_test).float()

In [40]:
np.random.seed(0)
torch.manual_seed(0)

w = torch.randn(13, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [41]:
for i in range(5000):
    with torch.no_grad():
        pred = x_t @ w + b
        loss = torch.mean((pred - y_t) ** 2)

        w_grad = 2/x_t.shape[0] * x_t.T @ (pred - y_t)
        b_grad = torch.mean(2 * (pred - y_t))

        w -= 0.01 * w_grad
        b -= 0.01 * b_grad

In [42]:
pred = x_test_t @ w + b
mean_squared_error(pred.detach().numpy(), y_test_t)

27.197708

In [43]:
np.random.seed(0)
torch.manual_seed(0)

w = torch.randn(13, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [44]:
for i in range(5000):
    pred = x_t @ w + b
    loss = torch.mean((pred - y_t) ** 2)
    loss.backward()

    with torch.no_grad():
        w -= 0.01 * w.grad
        b -= 0.01 * b.grad

    w.grad.zero_()
    b.grad.zero_()


In [45]:
pred = x_test_t @ w + b
mean_squared_error(pred.detach().numpy(), y_test_t)

27.197708

In [49]:
np.random.seed(0)
torch.manual_seed(0)

w = torch.randn(13, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [50]:
import torch.optim as optim
opt = optim.SGD([w, b], lr=0.01)

In [51]:
for i in range(5000):
    pred = x_t @ w + b
    loss = torch.mean((pred - y_t) ** 2)
    #print(loss)
    loss.backward()
    opt.step()

    opt.zero_grad()

In [52]:
pred = x_test_t @ w + b
mean_squared_error(pred.detach().numpy(), y_test_t)

27.197708

In [56]:
np.random.seed(0)
torch.manual_seed(0)

A = torch.randn(13, 40, requires_grad=True)
w = torch.randn(40, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [57]:
import torch.optim as optim
opt = optim.SGD([A, w, b], lr=0.005)

In [58]:
from torch.nn.functional import relu

for i in range(5000):
    pred = relu(x_t @ A) @ w + b
    loss = torch.mean((pred - y_t) ** 2)
    #print(loss.item())
    loss.backward()
    opt.step()

    opt.zero_grad()

In [59]:
pred = relu(x_test_t @ A) @ w + b
mean_squared_error(pred.detach().numpy(), y_test_t)

18.840103

In [60]:
a = torch.randn(10000, 10000)

In [61]:
a_numpy = a.numpy()

In [62]:
%%timeit
a_numpy.sum()

39.5 ms ± 491 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [63]:
%%timeit
a.sum()

34 ms ± 403 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [64]:
torch.cuda.is_available()

True

In [65]:
a = a.to("cuda")

In [66]:
%%timeit
a.sum()

1.44 ms ± 90.8 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)
